# Generated by Django 5.2.6 on 2025-09-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grand_nombre', models.BigIntegerField()),
                ('entier', models.IntegerField()),
                ('petit_entier', models.SmallIntegerField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flottant', models.FloatField()),
                ('positif', models.PositiveIntegerField()),
                ('positif_petit', models.PositiveSmallIntegerField()),
                ('est_actif', models.BooleanField(default=True)),
                ('est_visible', models.BooleanField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('date_naissance', models.DateField()),
                ('heure', models.TimeField()),
                ('date_heure', models.DateTimeField()),
                ('duree', models.DurationField()),
                ('dichier', models.FileField(upload_to='uploads/')),
                ('image', models.ImageField(upload_to='images/')),
                ('binaire', models.BinaryField()),
            ],
        ),
    ]
